### ISSUE TITLE
Please update clothFunction

### ISSUE THREAD

**Issue by v1rtl** [nikpundik/threejs-cloth-ES2015#1]
In the new three.js version, you have to pass a `target` where you apply your attributes to, to prevent repetitive object creation.

Here's a [thread](https://discourse.threejs.org/t/parametricgeometry-problem-with-parametric-function/3169) on official three.js forum

so we should replace this:

```js
import { Vector3 } from 'three';

export default {
  plane(width, height) {
    return (u, v) => {
      const x = (u - 0.5) * width;
      const y = (v + 0.5) * height;
      const z = 0;

      return new Vector3(x, y, z);
    };
  },
};
```

with this:

```js
import { Vector3 } from 'three';

export default {
  plane(width, height, target) {
    return (u, v, target) => {
      const x = (u - 0.5) * width;
      const y = (v + 0.5) * height;
      const z = 0;

      target.set(x, y, z)
    };
  },
};
```

**Comment by nikpundik** [comment]
Function replaced, thank you!

**Comment by v1rtl** [comment]
@nikpundik thanks for fixing it! I thought it is abandoned haha
